spring:
  datasource:
    url: jdbc:mysql://localhost:3306/radar_db?autoReconnect=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update